services:
  caddy:
    build: .
    image: ghcr.io/x13a/caddy-l4:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./config/:/etc/caddy/:ro
      - ./www/:/www/:ro
      - caddy_data:/data
      - caddy_config:/config
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider localhost:9000 || exit 1"]
      timeout: 5s
      start_period: 10s
    container_name: caddy
    networks:
      - proxy
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    env_file: ./caddy.env
    logging:
      options:
        max-size: 10m
        max-file: "5"

volumes:
  caddy_data:
    name: caddy_data
  caddy_config:
    name: caddy_config
