services:
  tg-proxy:
    build: https://github.com/geovex/tgp.git#v0.9.10
    image: tg-proxy
    container_name: tg-proxy
    restart: unless-stopped
    volumes:
      - ./config.toml:/app/config.toml:ro
    networks:
      - proxy
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    logging:
      options:
        max-size: 10m
        max-file: "5"

networks:
  proxy:
    external: true
