services:
  tg-proxy:
    image: nineseconds/mtg:2
    container_name: tg-proxy
    restart: unless-stopped
    volumes:
      - ./config.toml:/config.toml:ro
    networks:
      - proxy
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    logging:
      options:
        max-size: 10m
        max-file: "5"

networks:
  proxy:
    external: true
